spring.application.name=affordmed-evaluation-backend
server.port=8080

# External API Configuration
affordmed.base-url=http://4.224.186.213
affordmed.token=PASTE_YOUR_BEARER_TOKEN_HERE

# Logging Configuration
logging.level.root=INFO
logging.level.com.affordmed=DEBUG
